extend type Query {
  """
  ✨ Look up a single `Collection` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  collection(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Collection_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Collection_FirstRow
  ): Collection @fdc_generated(from: "Collection", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Draw` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  draw(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Draw_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Draw_FirstRow
  ): Draw @fdc_generated(from: "Draw", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Group` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  group(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Group_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Group_FirstRow
  ): Group @fdc_generated(from: "Group", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Loan` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  loan(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Loan_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Loan_FirstRow
  ): Loan @fdc_generated(from: "Loan", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Membership` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  membership(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Membership_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Membership_FirstRow
  ): Membership @fdc_generated(from: "Membership", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ List `Collection` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  collections(
    """
    Filter condition to narrow down the query results.
    """
    where: Collection_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Collection_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Collection_Having
  ): [Collection!]! @fdc_generated(from: "Collection", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Draw` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  draws(
    """
    Filter condition to narrow down the query results.
    """
    where: Draw_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Draw_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Draw_Having
  ): [Draw!]! @fdc_generated(from: "Draw", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Group` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  groups(
    """
    Filter condition to narrow down the query results.
    """
    where: Group_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Group_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Group_Having
  ): [Group!]! @fdc_generated(from: "Group", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Loan` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  loans(
    """
    Filter condition to narrow down the query results.
    """
    where: Loan_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Loan_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Loan_Having
  ): [Loan!]! @fdc_generated(from: "Loan", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Membership` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  memberships(
    """
    Filter condition to narrow down the query results.
    """
    where: Membership_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Membership_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Membership_Having
  ): [Membership!]! @fdc_generated(from: "Membership", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
}
